// P0 regression — Jumbo canonical-id v2.
//
// Context (2026-04-23): `pnpm run-jumbo` reported 30 inserted / 47 updated but
// the DB held only 14 distinct rows for source_id='jumbo-descuentos'. Root
// cause: the v1 id tuple (source_url, day_key, bank_key, pct, promo_type)
// collapsed multiple cuotas tiers on the same bank/day to the same id. The
// Cencopay block (3/6/12/18/24 cuotas all on "Todos los días") collapses
// 5 distinct promos into 1 row. The same applies to Galicia, Santander,
// Naranja X, and Comafi on the live page.
//
// Fix: the v2 tuple adds `variant_key` (cuotas_count for cuotas rows). These
// tests verify:
//
//   1. Two distinct cuotas tiers (3 vs 12) on same bank+day produce DIFFERENT
//      ids under v2.
//   2. Under v1 they would have collided (pinned by the v1 regression test
//      in supermarket-extract.test.ts).
//   3. Carrefour multi-bank promos with different bank compositions but
//      shared primary bank produce DIFFERENT ids under v2.
//   4. The cross-wallet universal block's ids don't collide with single-
//      wallet variants of the same pct/day.
//   5. Every id generated by the extractor from a realistic Jumbo payload
//      is unique (≥20 rows, zero intra-run collisions).
//   6. Existing idempotency of the extractor is preserved.
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

import { extractJumboPromos } from '../lib/jumbo-extract.js';
import { extractCarrefourPromos } from '../lib/carrefour-extract.js';
import { extractCotoPromos } from '../lib/coto-extract.js';
import {
  supermarketPromoId,
  supermarketPromoIdV1,
  dayKey,
  banksKey,
  walletsKey,
  variantKey,
} from '../lib/supermarket-extract.js';

const __dirname = dirname(fileURLToPath(import.meta.url));
const FIX_JUMBO = resolve(__dirname, '..', 'samples', 'long-tail', 'super', 'jumbo');

function usage() {
  return { input_tokens: 0, output_tokens: 0, thoughts_tokens: 0, cost_usd: 0 };
}

// =============================================================================
// 1. Cuotas tiers — 3 vs 12 on same bank+day yield distinct ids under v2
// =============================================================================

test('jumbo (P0 bug2): 3 vs 12 cuotas same bank+day yield DIFFERENT ids under v2', () => {
  const source_url = 'https://www.jumbo.com.ar/descuentos-del-dia';
  const day = dayKey([0, 1, 2, 3, 4, 5, 6]);
  const banks = banksKey(['cencopay']);
  const wallets = walletsKey([]);

  const id3 = supermarketPromoId({
    source_url,
    day_key: day,
    banks_key: banks,
    wallets_key: wallets,
    pct: 0,
    promo_type: 'cuotas',
    variant_key: variantKey({
      promo_type: 'cuotas',
      cuotas_count: 3,
      tope: null,
      tope_period: null,
    }),
  });
  const id12 = supermarketPromoId({
    source_url,
    day_key: day,
    banks_key: banks,
    wallets_key: wallets,
    pct: 0,
    promo_type: 'cuotas',
    variant_key: variantKey({
      promo_type: 'cuotas',
      cuotas_count: 12,
      tope: null,
      tope_period: null,
    }),
  });
  assert.notStrictEqual(id3, id12, 'v2: cuotas tiers distinguished');

  // And under v1, they WOULD collide — pinned in supermarket-extract.test.ts.
  const v1Shared = {
    source_url,
    day_key: day,
    bank_key: 'cencopay',
    pct: 0,
    promo_type: 'cuotas',
  };
  assert.strictEqual(
    supermarketPromoIdV1(v1Shared),
    supermarketPromoIdV1(v1Shared),
    'v1: 3 and 12 cuotas collide (bug pinned)',
  );
});

// =============================================================================
// 2. Multi-bank promos — different bank compositions with shared primary
//    yield different ids under v2 (v1 would collide)
// =============================================================================

test('carrefour (P0 bug2): multi-bank promos with shared primary yield DIFFERENT ids under v2', () => {
  const source_url = 'https://www.carrefour.com.ar/descuentos-bancarios';
  const day = dayKey([6]);
  const pct = 10;

  const aV2 = supermarketPromoId({
    source_url,
    day_key: day,
    banks_key: banksKey(['bbva', 'galicia']),
    wallets_key: walletsKey([]),
    pct,
    promo_type: 'cashback',
    variant_key: '',
  });
  const bV2 = supermarketPromoId({
    source_url,
    day_key: day,
    banks_key: banksKey(['bbva', 'santander']),
    wallets_key: walletsKey([]),
    pct,
    promo_type: 'cashback',
    variant_key: '',
  });
  assert.notStrictEqual(aV2, bV2, 'v2 distinguishes bank compositions');

  // v1: primaryBank([bbva, galicia]) === primaryBank([bbva, santander]) === 'bbva'
  const aV1 = supermarketPromoIdV1({
    source_url,
    day_key: day,
    bank_key: 'bbva',
    pct,
    promo_type: 'cashback',
  });
  const bV1 = supermarketPromoIdV1({
    source_url,
    day_key: day,
    bank_key: 'bbva',
    pct,
    promo_type: 'cashback',
  });
  assert.strictEqual(aV1, bV1, 'v1 would collide on multi-bank promos (bug pinned)');
});

// =============================================================================
// 3. Cross-wallet universal block — distinguishable from single-wallet variant
// =============================================================================

test('carrefour (P0 bug2): cross-wallet universal block has DIFFERENT id than single-wallet variant', () => {
  const source_url = 'https://www.carrefour.com.ar/descuentos-bancarios';
  const day = dayKey([6]);
  const pct = 10;

  const universal = supermarketPromoId({
    source_url,
    day_key: day,
    banks_key: banksKey(['carrefour']),
    wallets_key: walletsKey(['mercadopago', 'modo', 'cuentadni', 'uala', 'naranjax', 'personalpay', 'bna_plus', 'prex']),
    pct,
    promo_type: 'cashback',
    variant_key: '',
  });
  const modoOnly = supermarketPromoId({
    source_url,
    day_key: day,
    banks_key: banksKey(['carrefour']),
    wallets_key: walletsKey(['modo']),
    pct,
    promo_type: 'cashback',
    variant_key: '',
  });
  assert.notStrictEqual(universal, modoOnly, 'wallet composition enters id under v2');
});

// =============================================================================
// 4. Jumbo extractor emits ≥20 unique ids from a realistic payload
// =============================================================================

test('jumbo: realistic ≥20-promo payload yields ZERO intra-run id collisions', async () => {
  const source_url = 'https://www.jumbo.com.ar/descuentos-del-dia';
  // 25 realistic Jumbo-shaped promos including 5 cencopay cuotas tiers,
  // 4 galicia tiers, 3 santander variants, 2 patagonia pct tiers, etc.
  const promos = [
    // Cencopay cuotas tiers (the bug 2 smoking gun).
    { day_phrase: 'Todos los días', valid_days: [0,1,2,3,4,5,6], pct: 0, promo_type: 'cuotas', tope: null, tope_period: null, cuotas_count: 3, merchant: 'Jumbo', category: 'supermercado', issuer_bank: ['cencopay'], wallet: [], valid_regions: [], valid_from: '2026-04-01', valid_to: '2026-04-30', requires_min_spend: null },
    { day_phrase: 'Todos los días', valid_days: [0,1,2,3,4,5,6], pct: 0, promo_type: 'cuotas', tope: null, tope_period: null, cuotas_count: 6, merchant: 'Jumbo', category: 'supermercado', issuer_bank: ['cencopay'], wallet: [], valid_regions: [], valid_from: '2026-04-01', valid_to: '2026-04-30', requires_min_spend: null },
    { day_phrase: 'Todos los días', valid_days: [0,1,2,3,4,5,6], pct: 0, promo_type: 'cuotas', tope: null, tope_period: null, cuotas_count: 12, merchant: 'Jumbo', category: 'supermercado', issuer_bank: ['cencopay'], wallet: [], valid_regions: [], valid_from: '2026-04-01', valid_to: '2026-04-30', requires_min_spend: null },
    { day_phrase: 'Todos los días', valid_days: [0,1,2,3,4,5,6], pct: 0, promo_type: 'cuotas', tope: null, tope_period: null, cuotas_count: 18, merchant: 'Jumbo', category: 'supermercado', issuer_bank: ['cencopay'], wallet: [], valid_regions: [], valid_from: '2026-04-01', valid_to: '2026-04-30', requires_min_spend: null },
    { day_phrase: 'Todos los días', valid_days: [0,1,2,3,4,5,6], pct: 0, promo_type: 'cuotas', tope: null, tope_period: null, cuotas_count: 24, merchant: 'Jumbo', category: 'supermercado', issuer_bank: ['cencopay'], wallet: [], valid_regions: [], valid_from: '2026-04-01', valid_to: '2026-04-30', requires_min_spend: null },
    // Galicia cuotas tiers.
    { day_phrase: 'Todos los días', valid_days: [0,1,2,3,4,5,6], pct: 0, promo_type: 'cuotas', tope: null, tope_period: null, cuotas_count: 3, merchant: 'Jumbo', category: 'supermercado', issuer_bank: ['galicia'], wallet: [], valid_regions: [], valid_from: '2026-04-01', valid_to: '2026-04-30', requires_min_spend: null },
    { day_phrase: 'Todos los días', valid_days: [0,1,2,3,4,5,6], pct: 0, promo_type: 'cuotas', tope: null, tope_period: null, cuotas_count: 12, merchant: 'Jumbo', category: 'supermercado', issuer_bank: ['galicia'], wallet: [], valid_regions: [], valid_from: '2026-04-01', valid_to: '2026-04-30', requires_min_spend: null },
    { day_phrase: 'Jueves a Domingo', valid_days: [0,4,5,6], pct: 0, promo_type: 'cuotas', tope: null, tope_period: null, cuotas_count: 3, merchant: 'Jumbo', category: 'supermercado', issuer_bank: ['galicia'], wallet: [], valid_regions: [], valid_from: '2026-04-01', valid_to: '2026-04-30', requires_min_spend: null },
    // Santander.
    { day_phrase: 'Todos los días', valid_days: [0,1,2,3,4,5,6], pct: 0, promo_type: 'cuotas', tope: null, tope_period: null, cuotas_count: 3, merchant: 'Jumbo', category: 'supermercado', issuer_bank: ['santander'], wallet: [], valid_regions: [], valid_from: '2026-04-01', valid_to: '2026-04-30', requires_min_spend: null },
    { day_phrase: 'Todos los días', valid_days: [0,1,2,3,4,5,6], pct: 0, promo_type: 'cuotas', tope: null, tope_period: null, cuotas_count: 12, merchant: 'Jumbo', category: 'supermercado', issuer_bank: ['santander'], wallet: [], valid_regions: [], valid_from: '2026-04-01', valid_to: '2026-04-30', requires_min_spend: null },
    // Patagonia cashback tiers (different pct — already distinct under v1).
    { day_phrase: 'Sábados', valid_days: [6], pct: 30, promo_type: 'cashback', tope: 20000, tope_period: 'month', cuotas_count: null, merchant: 'Jumbo', category: 'supermercado', issuer_bank: ['patagonia'], wallet: [], valid_regions: [], valid_from: '2026-04-01', valid_to: '2026-04-30', requires_min_spend: null },
    { day_phrase: 'Sábados', valid_days: [6], pct: 35, promo_type: 'cashback', tope: 25000, tope_period: 'month', cuotas_count: null, merchant: 'Jumbo', category: 'supermercado', issuer_bank: ['patagonia'], wallet: [], valid_regions: [], valid_from: '2026-04-01', valid_to: '2026-04-30', requires_min_spend: null },
    // Macro, Nacion, Comafi cuotas.
    { day_phrase: 'Todos los días', valid_days: [0,1,2,3,4,5,6], pct: 0, promo_type: 'cuotas', tope: null, tope_period: null, cuotas_count: 6, merchant: 'Jumbo', category: 'supermercado', issuer_bank: ['macro'], wallet: [], valid_regions: [], valid_from: '2026-04-01', valid_to: '2026-04-30', requires_min_spend: null },
    { day_phrase: 'Todos los días', valid_days: [0,1,2,3,4,5,6], pct: 0, promo_type: 'cuotas', tope: null, tope_period: null, cuotas_count: 12, merchant: 'Jumbo', category: 'supermercado', issuer_bank: ['macro'], wallet: [], valid_regions: [], valid_from: '2026-04-01', valid_to: '2026-04-30', requires_min_spend: null },
    { day_phrase: 'Todos los días', valid_days: [0,1,2,3,4,5,6], pct: 0, promo_type: 'cuotas', tope: null, tope_period: null, cuotas_count: 12, merchant: 'Jumbo', category: 'supermercado', issuer_bank: ['nacion'], wallet: [], valid_regions: [], valid_from: '2026-04-01', valid_to: '2026-04-30', requires_min_spend: null },
    { day_phrase: 'Todos los días', valid_days: [0,1,2,3,4,5,6], pct: 0, promo_type: 'cuotas', tope: null, tope_period: null, cuotas_count: 3, merchant: 'Jumbo', category: 'supermercado', issuer_bank: ['comafi'], wallet: [], valid_regions: [], valid_from: '2026-04-01', valid_to: '2026-04-30', requires_min_spend: null },
    { day_phrase: 'Vie a Dom', valid_days: [0,5,6], pct: 0, promo_type: 'cuotas', tope: null, tope_period: null, cuotas_count: 12, merchant: 'Jumbo', category: 'supermercado', issuer_bank: ['comafi'], wallet: [], valid_regions: [], valid_from: '2026-04-01', valid_to: '2026-04-30', requires_min_spend: null },
    // Naranja X Plan Z (cuotas_count 3) + different Naranja X row (cuotas_count 6).
    { day_phrase: 'Todos los días', valid_days: [0,1,2,3,4,5,6], pct: 0, promo_type: 'cuotas', tope: null, tope_period: null, cuotas_count: 3, merchant: 'Jumbo', category: 'supermercado', issuer_bank: ['naranjax'], wallet: [], valid_regions: [], valid_from: '2026-04-01', valid_to: '2026-04-30', requires_min_spend: null },
    { day_phrase: 'Todos los días', valid_days: [0,1,2,3,4,5,6], pct: 0, promo_type: 'cuotas', tope: null, tope_period: null, cuotas_count: 6, merchant: 'Jumbo', category: 'supermercado', issuer_bank: ['naranjax'], wallet: [], valid_regions: [], valid_from: '2026-04-01', valid_to: '2026-04-30', requires_min_spend: null },
    // Visa/Mastercard no-bank.
    { day_phrase: 'Todos los días', valid_days: [0,1,2,3,4,5,6], pct: 0, promo_type: 'cuotas', tope: null, tope_period: null, cuotas_count: 3, merchant: 'Jumbo', category: 'supermercado', issuer_bank: [], wallet: [], card_brand: ['visa','mastercard'], valid_regions: [], valid_from: '2026-04-01', valid_to: '2026-04-30', requires_min_spend: null },
    // Galicia cashback extra tiers.
    { day_phrase: 'Martes', valid_days: [2], pct: 20, promo_type: 'cashback', tope: 15000, tope_period: 'week', cuotas_count: null, merchant: 'Jumbo', category: 'supermercado', issuer_bank: ['galicia'], wallet: [], valid_regions: [], valid_from: '2026-04-01', valid_to: '2026-04-30', requires_min_spend: null },
    { day_phrase: 'Martes', valid_days: [2], pct: 25, promo_type: 'cashback', tope: 20000, tope_period: 'week', cuotas_count: null, merchant: 'Jumbo', category: 'supermercado', issuer_bank: ['galicia'], wallet: [], valid_regions: [], valid_from: '2026-04-01', valid_to: '2026-04-30', requires_min_spend: null },
    // BBVA cashback.
    { day_phrase: 'Jueves', valid_days: [4], pct: 20, promo_type: 'cashback', tope: 12000, tope_period: 'week', cuotas_count: null, merchant: 'Jumbo', category: 'supermercado', issuer_bank: ['bbva'], wallet: [], valid_regions: [], valid_from: '2026-04-01', valid_to: '2026-04-30', requires_min_spend: null },
    // MODO wallet cashback.
    { day_phrase: 'Viernes', valid_days: [5], pct: 15, promo_type: 'cashback', tope: 8000, tope_period: 'week', cuotas_count: null, merchant: 'Jumbo', category: 'supermercado', issuer_bank: [], wallet: ['modo'], valid_regions: [], valid_from: '2026-04-01', valid_to: '2026-04-30', requires_min_spend: null },
    // Cuenta DNI wallet.
    { day_phrase: 'Miércoles', valid_days: [3], pct: 25, promo_type: 'cashback', tope: 18000, tope_period: 'month', cuotas_count: null, merchant: 'Jumbo', category: 'supermercado', issuer_bank: [], wallet: ['cuentadni'], valid_regions: [], valid_from: '2026-04-01', valid_to: '2026-04-30', requires_min_spend: null },
  ];
  assert.strictEqual(promos.length, 25);

  const result = await extractJumboPromos({
    source_url,
    markdown: 'md',
    llmOverride: async () => ({ data: { promos: promos as any }, usage: usage() }),
  });
  assert.strictEqual(
    result.rejected_count,
    0,
    `no rejects: ${result.rejected_reasons.join('; ')}`,
  );
  assert.strictEqual(result.promos.length, 25, 'all 25 rows preserved — no id collapse');
  assert.strictEqual(new Set(result.ids).size, 25, 'zero id collisions');
});

// =============================================================================
// 5. Idempotency: two back-to-back runs with identical input → identical ids
// =============================================================================

test('jumbo: canonical-id v2 is stable across identical runs', async () => {
  const raw = await readFile(resolve(FIX_JUMBO, 'descuentos-del-dia.extract.json'), 'utf8');
  const fx = JSON.parse(raw) as { source_url: string; data: { promos: any[] } };
  const stub = async () => ({ data: { promos: fx.data.promos }, usage: usage() });

  const run1 = await extractJumboPromos({ source_url: fx.source_url, markdown: 'md', llmOverride: stub });
  const run2 = await extractJumboPromos({ source_url: fx.source_url, markdown: 'md', llmOverride: stub });
  assert.deepStrictEqual(run1.ids, run2.ids);
});

// =============================================================================
// 6. Cross-source non-regression — Coto + Carrefour still emit zero-collision
// =============================================================================

test('coto: fixture still emits zero intra-run id collisions (no regression)', async () => {
  const FIX_COTO = resolve(__dirname, '..', 'samples', 'long-tail', 'super', 'coto');
  const raw = await readFile(resolve(FIX_COTO, 'cotodigital-descuentos.extract.json'), 'utf8');
  const fx = JSON.parse(raw) as { source_url: string; data: { promos: any[] } };

  const result = await extractCotoPromos({
    source_url: fx.source_url,
    markdown: 'md',
    llmOverride: async () => ({ data: { promos: fx.data.promos }, usage: usage() }),
  });
  assert.strictEqual(result.rejected_count, 0);
  assert.strictEqual(new Set(result.ids).size, result.ids.length, 'coto: no collisions');
});

test('carrefour: fixture still emits zero intra-run id collisions (no regression)', async () => {
  const FIX_CAR = resolve(__dirname, '..', 'samples', 'long-tail', 'super', 'carrefour');
  const raw = await readFile(resolve(FIX_CAR, 'descuentos-bancarios.extract.json'), 'utf8');
  const fx = JSON.parse(raw) as { source_url: string; data: { promos: any[] } };

  const result = await extractCarrefourPromos({
    source_url: fx.source_url,
    markdown: 'md',
    llmOverride: async () => ({ data: { promos: fx.data.promos }, usage: usage() }),
  });
  assert.strictEqual(result.rejected_count, 0);
  assert.strictEqual(new Set(result.ids).size, result.ids.length, 'carrefour: no collisions');
});
